import os

from .paths import FIGURES_DIR, OUTPUT_DIR
from .plots import build_all_figures
from .style import apply_matplotlib_style
from .thread_scaling_appendix import generate_thread_scaling_appendix_tables


FIGURE_INDEX = [
    ("01_overview_runtime_vs_n.png", "Overall runtime overview across versions"),
    ("03_overview_speedup_vs_v0.png", "Speedup against the baseline"),
    ("04_representative_runtime_bars.png", "Representative runtime summary"),
    ("05_representative_gflops_bars.png", "Representative throughput summary"),
    ("10_pair_v0_to_v1_runtime.png", "Pairwise runtime comparison: v0 to v1"),
    ("11_pair_v0_to_v1_gflops.png", "Pairwise GFLOP/s comparison: v0 to v1"),
    ("12_pair_v1_to_v2_runtime.png", "Pairwise runtime comparison: v1 to v2"),
    ("13_pair_v1_to_v2_gflops.png", "Pairwise GFLOP/s comparison: v1 to v2"),
    ("14_pair_v2_to_v3_runtime.png", "Pairwise runtime comparison: v2 to v3"),
    ("15_pair_v2_to_v3_gflops.png", "Pairwise GFLOP/s comparison: v2 to v3"),
    ("16_pair_v3_to_final_runtime.png", "Pairwise runtime comparison: v3 to v4 Final Version"),
    ("17_pair_v3_to_final_gflops.png", "Pairwise GFLOP/s comparison: v3 to v4 Final Version"),
    ("18_pair_v2_to_final_runtime.png", "Pairwise runtime comparison: v2 to v4 Final Version"),
    ("19_pair_v2_to_final_gflops.png", "Pairwise GFLOP/s comparison: v2 to v4 Final Version"),
    ("20_parallel_runtime_v3_v4.png", "Parallel-era runtime comparison"),
    ("21_thread_scaling_runtime.png", "Thread scaling runtime"),
    ("22_thread_scaling_speedup_efficiency.png", "Thread scaling speedup and efficiency"),
    ("23_v4_thread_scaling_distribution.png", "Per-run thread scaling distribution for v4 Final Version"),
    ("30_v4_schedule_study.png", "Current v4 Final Version schedule study"),
    ("31_v3_v4_schedule_comparison.png", "Schedule sensitivity across v3 and v4 Final Version"),
    ("40_boundary_sizes_v2_v3_v4.png", "Boundary-size behavior"),
    ("41_v4_block_repeatability.png", "v4 Final Version repeatability and block-size behavior"),
    ("42_v4_block_invariance.png", "v4 Final Version block invariance"),
    ("50_ipc_vs_n.png", "IPC over matrix size"),
    ("51_cache_miss_pct_vs_n.png", "Cache-miss percentage over matrix size"),
    ("52_cycles_vs_n.png", "Raw cycle count over matrix size"),
    ("53_v0_v1_ipc_vs_n.png", "Focused IPC comparison for v0 and v1"),
    ("60_extended_thread_scaling_n256.png", "Extended thread scaling comparison at n=256"),
    ("61_extended_thread_scaling_n1024.png", "Extended thread scaling comparison at n=1024"),
    ("62_extended_thread_scaling_n2048.png", "Extended thread scaling comparison at n=2048"),
    ("63_v4_speedup_vs_threads_multi_n.png", "v4 Final Version speedup vs threads for n=256, 1024, and 2048"),
]


def _write_figure_index():
    path = os.path.join(OUTPUT_DIR, "figure_index.md")
    with open(path, "w") as handle:
        handle.write("# Figure Index\n\n")
        handle.write("Generated by `python3 perf_analysis/run_all.py`.\n\n")
        for filename, description in FIGURE_INDEX:
            handle.write("- `%s`: %s\n" % (filename, description))


def main():
    if not os.path.isdir(FIGURES_DIR):
        os.makedirs(FIGURES_DIR)
    apply_matplotlib_style()
    build_all_figures()
    generate_thread_scaling_appendix_tables()
    _write_figure_index()
    print("Generated %d figures under %s" % (len(FIGURE_INDEX), FIGURES_DIR))
